services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.2.3
    container_name: g_filebeat
    restart: on-failure
    depends_on:
      - mysql
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./data/mysql/mysql:/var/log/mysql
      - filebeat_data:/usr/share/filebeat/data/
    networks:
      - graylog  

  mysql:
    container_name: g_mysql
    platform: linux/amd64
    image: mysql:latest
    restart: always    
    environment: 
      - MYSQL_DATABASE=graylog
      - MYSQL_ROOT_PASSWORD=Qwerty123
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
      - ./load.sql:/data/load.sql
    ports:
      - 3306:3306
    networks:
      - graylog

  mongodb:
    image: mongo:4.2
    container_name: g_mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: g_es    
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.3
    container_name: g_graylog
    volumes:
      - graylog_data:/usr/share/graylog/data
      - ./plugin:/usr/share/graylog/plugin
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - elasticsearch
      - mysql
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
      - mysql
    ports:
      - 9000:9000
      - 5044:5044
    networks:
      - graylog

networks:
  graylog:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local
  filebeat_data:
    driver: local
