services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.2.3
    container_name: elk_filebeat
    restart: on-failure
    depends_on:
      - mysql
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./data/mysql/mysql/:/var/log/mysql/mysql-slow.log
      - filebeat_data:/usr/share/filebeat/data/
    networks:
      - elk

  mysql:
    image: mysql:latest
    restart: always
    container_name: elk_mysql
    environment:  
      - MYSQL_DATABASE=elk
      - MYSQL_ROOT_PASSWORD=Qwerty123
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
      - ./load.sql:/data/load.sql
    ports:
      - 3306:3306
    networks:
      - elk
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
    container_name: elk_es
    tty: true
    privileged: true
    stdin_open: true
    environment:
      - node.name=elasticsearch
      - cluster.name=log-cluster
      - discovery.seed_hosts=elasticsearch
      - discovery.type=single-node
      - cluster.routing.allocation.enable=all
      - ELASTIC_PASSWORD=qwerty
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.1
    container_name: elk_logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: qwerty
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.1
    container_name: elk_kibana
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=qwerty
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  es_data:
    driver: local
  kibana_data:
    driver: local
  filebeat_data:
    driver: local

networks:
  elk:
    driver: bridge
